name: minbymin

on:
  schedule:
    - cron: '*/5 * * * *' #Execute every 59 mins
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
      
      - name: Install dependencies
        run: |
          python -m pip install --pandas
          python -m pip install --numpy
          python -m pip install --matplotlib
          python -m pip install --seaborn
          python -m pip install --plotly
          python -m pip install --sentence transformers
          
      - name: Execute Python Script
        run: python "Test EDA for GitHub Actions PoC.py"
