name: minbymin

on:
  schedule:
    - cron: '*/5 * * * *' #Execute every 59 mins
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
          
      - name: Execute Python Script
        run: python openFile.py