name: minbymin

on:
  schedule:
    - cron: '0 */21 * * *' #Execute every 21 hours
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      
      - name: Install dependencies
      #  run: |
      #       python -m pip install --upgrade pip
      #       python -m pip install -r "SentimentAnalysis/requirements.txt"
          
      - name: Execute Python Script
        run: python "openFile.py"

      - name: Update the repository
        run: git push
