name: minbymin

on:
  schedule:
    - cron: '*/59 * * * *' #Execute every 59 mins
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             python -m pip install -r "SentimentAnalysis/requirements.txt"
          
      - name: Execute Python Script
        run: python "SentimentAnalysis/sentiment_analysis_week0903.py"
